# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d1061cf328b89010a441a9ef79e3cecf62be1e794c615f946db2098e6b5ab8172f7301a969a4ff9eaec1d5907cf4aa62c298680dc6b4c728425c566bc5a4fc4f

test:
  domain_name: example.com 
  secret_key_base: d1532e5c259c9be107cb19b6f8b25b8cd09fa6dc43de8eb32d26e24ffd52b10c2969f7939d8612586afefa93407a2c178d427da32aa9792ff1f8a7d62b1ad705

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
